/* GD32F103C8T6 asynchronous RS-232 bridge 1.1.0.
 * Pin mapping: supplied Э3.pdf sheets 8/9, DD9/DD11, MAX3238 DD10/DD12.
 * No generated bytes, HDLC encoding or synchronous output clock. */
#include "gd32f10x.h"
#include "bridge.h"

#ifndef HOST_BAUD
#define HOST_BAUD 38400U
#endif
#ifndef LOGGER_BAUD
#define LOGGER_BAUD 38400U
#endif
#if HXTAL_VALUE != 16000000U
#error This board requires a 16 MHz external crystal
#endif
#define STR_INNER(x) #x
#define STR(x) STR_INNER(x)
__attribute__((section(".version"), used))
const char firmware_version[] = "lazarus-gd32-rs232-1.1.0 GD32F103C8T6 HSE16MHz"
    " host=" STR(HOST_BAUD) " logger=" STR(LOGGER_BAUD) " 8N1";

bridge_t bridge;
static volatile uint32_t ticks;

static void fatal_error(void) {
    __disable_irq();
    /* SWD remains enabled. Once started, watchdog resets after a fault. */
    for (;;) { __NOP(); }
}

static void board_init(void) {
    rcu_periph_clock_enable(RCU_AF);
    rcu_periph_clock_enable(RCU_GPIOA);
    rcu_periph_clock_enable(RCU_GPIOB);
    gpio_pin_remap_config(GPIO_USART0_REMAP, DISABLE);
    gpio_pin_remap_config(GPIO_USART1_REMAP, DISABLE);

    /* Disable MAX3238 until all transmitter inputs have defined levels. */
    gpio_bit_reset(GPIOB, GPIO_PIN_1);
    gpio_bit_set(GPIOB, GPIO_PIN_2);
    gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_2MHZ, GPIO_PIN_1 | GPIO_PIN_2);

    /* RTS (PA1) and DTR (PA4) asserted continuously: TTL 0 becomes positive
     * RS-232 through MAX3238. CTS/DSR are not used for flow control. */
    gpio_bit_reset(GPIOA, GPIO_PIN_1 | GPIO_PIN_4);
    gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_2MHZ, GPIO_PIN_1 | GPIO_PIN_4);
    gpio_init(GPIOA, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_2MHZ, GPIO_PIN_0 | GPIO_PIN_5);
    gpio_init(GPIOB, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_2MHZ, GPIO_PIN_0);

    /* Idle-high TX before routing hardware USART outputs. */
    gpio_bit_set(GPIOA, GPIO_PIN_9 | GPIO_PIN_2);
    gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_9 | GPIO_PIN_2);
    gpio_init(GPIOA, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_2MHZ, GPIO_PIN_10 | GPIO_PIN_3);
    /* PC13 is NC on the actual board. PA13/PA14 remain SWD. */
}

static void uart_init(uint32_t u, uint32_t baud) {
    usart_deinit(u);
    usart_baudrate_set(u, baud);
    usart_word_length_set(u, USART_WL_8BIT);
    usart_stop_bit_set(u, USART_STB_1BIT);
    usart_parity_config(u, USART_PM_NONE);
    usart_hardware_flow_rts_config(u, USART_RTS_DISABLE);
    usart_hardware_flow_cts_config(u, USART_CTS_DISABLE);
    usart_receive_config(u, USART_RECEIVE_ENABLE);
    usart_transmit_config(u, USART_TRANSMIT_ENABLE);
    usart_enable(u);
    volatile uint32_t discarded = USART_STAT(u);
    discarded = USART_DATA(u);
    (void)discarded;
    USART_CTL2(u) |= USART_CTL2_ERRIE;
    USART_CTL0(u) |= USART_CTL0_RBNEIE;
}

static void uart_irq(uint32_t u, uint32_t peer, unsigned src) {
    const uint32_t stat = USART_STAT(u);
    const uint32_t error_mask = USART_STAT_PERR | USART_STAT_FERR |
                                USART_STAT_NERR | USART_STAT_ORERR;
    if (stat & (USART_STAT_RBNE | error_mask)) {
        /* GD32: read STAT followed by DATA to clear receive/error flags. */
        uint8_t byte = (uint8_t)USART_DATA(u);
        unsigned errors = 0;
        if (stat & USART_STAT_PERR) errors |= BRIDGE_PARITY;
        if (stat & USART_STAT_FERR) errors |= BRIDGE_FRAMING;
        if (stat & USART_STAT_NERR) errors |= BRIDGE_NOISE;
        if (stat & USART_STAT_ORERR) errors |= BRIDGE_OVERRUN;
        if (bridge_receive(&bridge, src, (stat & USART_STAT_RBNE) != 0,
                           byte, errors)) USART_CTL0(peer) |= USART_CTL0_TBEIE;
    }
    if ((stat & USART_STAT_TBE) && (USART_CTL0(u) & USART_CTL0_TBEIE)) {
        uint8_t byte;
        if (bridge_next_tx(&bridge, src, &byte)) USART_DATA(u) = byte;
        else USART_CTL0(u) &= ~USART_CTL0_TBEIE;
    }
}

void USART0_IRQHandler(void) { uart_irq(USART0, USART1, BRIDGE_HOST); }
void USART1_IRQHandler(void) { uart_irq(USART1, USART0, BRIDGE_LOGGER); }
void SysTick_Handler(void) { ticks++; }
void HardFault_Handler(void) { fatal_error(); }
void MemManage_Handler(void) { fatal_error(); }
void BusFault_Handler(void) { fatal_error(); }
void UsageFault_Handler(void) { fatal_error(); }

int main(void) {
    /* Vendor SystemInit selects HXTAL directly: core/APB1/APB2 16 MHz. */
    SystemCoreClockUpdate();
    if (SystemCoreClock != 16000000U ||
        rcu_clock_freq_get(CK_APB2) != 16000000U ||
        rcu_clock_freq_get(CK_APB1) != 16000000U) fatal_error();
    board_init();
    rcu_periph_clock_enable(RCU_USART0);
    rcu_periph_clock_enable(RCU_USART1);
    uart_init(USART0, HOST_BAUD);
    uart_init(USART1, LOGGER_BAUD);
    gpio_init(GPIOA, GPIO_MODE_AF_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_9 | GPIO_PIN_2);
    /* ~FORCEOFF=1, FORCEON=1: transceiver always on. */
    gpio_bit_set(GPIOB, GPIO_PIN_1 | GPIO_PIN_2);

    /* Equal preemption priority serializes every shared queue access. */
    NVIC_SetPriorityGrouping(3U);
    NVIC_SetPriority(USART0_IRQn, 1U);
    NVIC_SetPriority(USART1_IRQn, 1U);
    NVIC_EnableIRQ(USART0_IRQn);
    NVIC_EnableIRQ(USART1_IRQn);
    if (SysTick_Config(SystemCoreClock / 1000U)) fatal_error();
    NVIC_SetPriority(SysTick_IRQn, 15U);
    rcu_osci_on(RCU_IRC40K);
    if (rcu_osci_stab_wait(RCU_IRC40K) != SUCCESS) fatal_error();
    if (fwdgt_config(2000U, FWDGT_PSC_DIV64) != SUCCESS) fatal_error();
    fwdgt_counter_reload();
    fwdgt_enable();
    uint32_t last = ticks;
    for (;;) {
        if ((uint32_t)(ticks - last) >= 500U) {
            fwdgt_counter_reload();
            last = ticks;
        }
        __WFI();
    }
}
